<a href="https://colab.research.google.com/github/mjaffry/NLP_Research/blob/master/NLP_Learning01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [48]:
import spacy
from spacy import displacy

In [49]:
nlp = spacy.load('en_core_web_sm')  

In [50]:
text = "Apple, This is first sentence. and Google this is another one. here 3rd one is"

In [51]:
doc = nlp(text)

In [52]:
doc

Apple, This is first sentence. and Google this is another one. here 3rd one is

In [53]:
for token in doc:
    print(token)

Apple
,
This
is
first
sentence
.
and
Google
this
is
another
one
.
here
3rd
one
is


In [54]:
sent = nlp.create_pipe('sentencizer')

In [55]:
nlp.add_pipe(sent, before='parser')

In [56]:
doc = nlp(text)

In [57]:
for sent in doc.sents:
    print(sent)

Apple, This is first sentence.
and Google this is another one.
here 3rd one is


In [58]:
from spacy.lang.en.stop_words import STOP_WORDS

In [59]:
stopwords = list(STOP_WORDS)

In [60]:
print(stopwords)

['own', 'thus', 'as', 'take', 'whose', '’s', 'front', 'cannot', 'part', 'ours', 'down', 'below', 'well', 'therein', 'show', 'everyone', 'an', 'yours', 'since', 'has', 'i', 'others', 'hers', 'something', 'almost', 'due', 'would', 'yet', 'n’t', 'six', 'after', 'hence', 'regarding', 'through', '’d', 'he', 'his', 'really', 'ten', 'these', 'whatever', 'least', 'behind', 'became', 'made', 'on', 'around', 'except', 'every', 'but', 'call', 'hereby', 'might', 'various', 'me', 'we', 'nothing', 'sometime', 'anyone', 'among', 'itself', 'all', 'no', 'then', 'did', 'give', 'upon', 'some', 'here', 'a', 'across', 'than', 'thereafter', 'toward', 'else', 'amongst', 'formerly', 'not', 'five', 'already', 'noone', "'re", 'often', 'such', 'any', "'s", 'next', 'other', 'is', 'elsewhere', 'afterwards', 'thru', 'was', 'still', 'herein', 'last', 'everything', 'wherever', 'there', 'do', 'rather', '‘m', 'beside', 'becomes', 'or', 'whereupon', "n't", 'into', 'those', '’m', 'get', 'had', 'herself', 'must', 'thereby

In [61]:
len(stopwords)

326

In [62]:
for token in doc:
    if token.is_stop == False:
        print(token)

Apple
,
sentence
.
Google
.
3rd


In [63]:
doc = nlp('run runs running runner')

In [64]:
doc = nlp('All is well at your end!')

In [65]:
for token in doc:
    print(token.text, token.pos_)

All DET
is AUX
well ADV
at ADP
your DET
end NOUN
! PUNCT


In [66]:
displacy.render(doc, style = 'dep',jupyter=True)

In [67]:
doc = nlp("New York City on Tuesday declared a public health emergency and ordered mandatory measles vaccinations amid an outbreak, becoming the latest national flash point over refusals to inoculate against dangerous diseases. At least 285 people have contracted measles in the city since September, mostly in Brooklyn’s Williamsburg neighborhood. The order covers four Zip codes there, Mayor Bill de Blasio (D) said Tuesday. The mandate orders all unvaccinated people in the area, including a concentration of Orthodox Jews, to receive inoculations, including for children as young as 6 months old. Anyone who resists could be fined up to $1,000.")

In [68]:
doc

New York City on Tuesday declared a public health emergency and ordered mandatory measles vaccinations amid an outbreak, becoming the latest national flash point over refusals to inoculate against dangerous diseases. At least 285 people have contracted measles in the city since September, mostly in Brooklyn’s Williamsburg neighborhood. The order covers four Zip codes there, Mayor Bill de Blasio (D) said Tuesday. The mandate orders all unvaccinated people in the area, including a concentration of Orthodox Jews, to receive inoculations, including for children as young as 6 months old. Anyone who resists could be fined up to $1,000.

In [70]:

displacy.render(doc, style = 'ent',jupyter=True)

In [72]:
import pandas as pd

In [71]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [75]:
data_yelp = pd.read_csv('https://raw.githubusercontent.com/laxmimerit/NLP-Tutorial-8---Sentiment-Classification-using-SpaCy-for-IMDB-and-Amazon-Review-Dataset/master/datasets/yelp_labelled.txt', sep='\t', header = None)

0  1
0                             Wow... Loved this place.  1
1                                   Crust is not good.  0
2            Not tasty and the texture was just nasty.  0
3    Stopped by during the late May bank holiday of...  1
4    The selection on the menu was great and so wer...  1
..                                                 ... ..
995  I think food should have flavor and texture an...  0
996                           Appetite instantly gone.  0
997  Overall I was not impressed and would not go b...  0
998  The whole experience was underwhelming, and I ...  0
999  Then, as if I hadn't wasted enough of my life ...  0

[1000 rows x 2 columns]

In [76]:
data_yelp.head()

0  1
0                           Wow... Loved this place.  1
1                                 Crust is not good.  0
2          Not tasty and the texture was just nasty.  0
3  Stopped by during the late May bank holiday of...  1
4  The selection on the menu was great and so wer...  1

In [78]:
columns_name = ['Review', 'Sentiment']
data_yelp.columns = columns_name
data_yelp

Review  Sentiment
0                             Wow... Loved this place.          1
1                                   Crust is not good.          0
2            Not tasty and the texture was just nasty.          0
3    Stopped by during the late May bank holiday of...          1
4    The selection on the menu was great and so wer...          1
..                                                 ...        ...
995  I think food should have flavor and texture an...          0
996                           Appetite instantly gone.          0
997  Overall I was not impressed and would not go b...          0
998  The whole experience was underwhelming, and I ...          0
999  Then, as if I hadn't wasted enough of my life ...          0

[1000 rows x 2 columns]

In [79]:
data_yelp.shape

(1000, 2)

In [81]:
data_amazon = pd.read_csv('https://raw.githubusercontent.com/laxmimerit/NLP-Tutorial-8---Sentiment-Classification-using-SpaCy-for-IMDB-and-Amazon-Review-Dataset/master/datasets/amazon_cells_labelled.txt', sep = '\t', header = None)
data_amazon.columns = columns_name
data_amazon

Review  Sentiment
0    So there is no way for me to plug it in here i...          0
1                          Good case, Excellent value.          1
2                               Great for the jawbone.          1
3    Tied to charger for conversations lasting more...          0
4                                    The mic is great.          1
..                                                 ...        ...
995  The screen does get smudged easily because it ...          0
996  What a piece of junk.. I lose more calls on th...          0
997                       Item Does Not Match Picture.          0
998  The only thing that disappoint me is the infra...          0
999  You can not answer calls with the unit, never ...          0

[1000 rows x 2 columns]

In [82]:
data_imdb = pd.read_csv('https://raw.githubusercontent.com/laxmimerit/NLP-Tutorial-8---Sentiment-Classification-using-SpaCy-for-IMDB-and-Amazon-Review-Dataset/master/datasets/imdb_labelled.txt', sep = '\t', header = None)

In [83]:
data_imdb

0  1
0    A very, very, very slow-moving, aimless movie ...  0
1    Not sure who was more lost - the flat characte...  0
2    Attempting artiness with black & white and cle...  0
3         Very little music or anything to speak of.    0
4    The best scene in the movie was when Gerardo i...  1
..                                                 ... ..
743  I just got bored watching Jessice Lange take h...  0
744  Unfortunately, any virtue in this film's produ...  0
745                   In a word, it is embarrassing.    0
746                               Exceptionally bad!    0
747  All in all its an insult to one's intelligence...  0

[748 rows x 2 columns]

In [84]:
data_imdb.columns = columns_name

In [85]:
data_imdb.shape

(748, 2)

In [86]:
data_imdb.head()

Review  Sentiment
0  A very, very, very slow-moving, aimless movie ...          0
1  Not sure who was more lost - the flat characte...          0
2  Attempting artiness with black & white and cle...          0
3       Very little music or anything to speak of.            0
4  The best scene in the movie was when Gerardo i...          1

In [87]:
data = data_yelp.append([data_amazon, data_imdb], ignore_index=True)

In [88]:
data

Review  Sentiment
0                              Wow... Loved this place.          1
1                                    Crust is not good.          0
2             Not tasty and the texture was just nasty.          0
3     Stopped by during the late May bank holiday of...          1
4     The selection on the menu was great and so wer...          1
...                                                 ...        ...
2743  I just got bored watching Jessice Lange take h...          0
2744  Unfortunately, any virtue in this film's produ...          0
2745                   In a word, it is embarrassing.            0
2746                               Exceptionally bad!            0
2747  All in all its an insult to one's intelligence...          0

[2748 rows x 2 columns]

In [89]:
data.shape

(2748, 2)

In [90]:
data.head()

Review  Sentiment
0                           Wow... Loved this place.          1
1                                 Crust is not good.          0
2          Not tasty and the texture was just nasty.          0
3  Stopped by during the late May bank holiday of...          1
4  The selection on the menu was great and so wer...          1

In [91]:
data['Sentiment'].value_counts()

1    1386
0    1362
Name: Sentiment, dtype: int64

In [92]:
data.isnull().sum()

Review       0
Sentiment    0
dtype: int64

# Tokenization

In [93]:
import string

In [94]:
punct = string.punctuation

In [95]:
punct

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [97]:
def text_data_cleaning(sentence):
    doc = nlp(sentence)
    
    tokens = []
    for token in doc:
        if token.lemma_ != "-PRON-":
            temp = token.lemma_.lower().strip()
        else:
            temp = token.lower_
        tokens.append(temp)
    
    cleaned_tokens = []
    for token in tokens:
        if token not in stopwords and token not in punct:
            cleaned_tokens.append(token)
    return cleaned_tokens

In [99]:
text_data_cleaning("Hello how are you. Like this video")

['hello', 'like', 'video']

# Vectorization Feature Engineering (TF-IDF)

In [100]:
from sklearn.svm import LinearSVC

In [102]:
tfidf = TfidfVectorizer(tokenizer = text_data_cleaning)
classifier = LinearSVC()
classifier

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

In [103]:
X = data['Review']
y = data['Sentiment']

In [104]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [105]:
X_train.shape, X_test.shape

((2198,), (550,))

In [106]:
clf = Pipeline([('tfidf', tfidf), ('clf', classifier)])

In [107]:
clf.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('tfidf',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=<function text_data_cleaning at 0x7f0d35519620>,
                                 use_idf=True, vocabulary=None)),
                ('clf',
                 LinearSVC(C=1.0, class_weight=None, dual=True,
                           fit_intercept

In [108]:
y_pred = clf.predict(X_test)

In [109]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.77      0.82      0.80       285
           1       0.79      0.74      0.77       265

    accuracy                           0.78       550
   macro avg       0.78      0.78      0.78       550
weighted avg       0.78      0.78      0.78       550



In [110]:
confusion_matrix(y_test, y_pred)

array([[233,  52],
       [ 68, 197]])

In [111]:
clf.predict(['Wow, this is amzing lesson'])

array([1])

In [112]:
clf.predict(['Wow, this sucks'])

array([0])

In [113]:
clf.predict(['Worth of watching it. Please like it'])

array([1])

In [114]:
clf.predict(['Loved it. amazing'])

array([1])